import { Component } from '@angular/core';

@Component({
  selector: 'app-snooker',
  templateUrl: './snooker.component.html',
  styleUrls: ['./snooker.component.css']
})
export class SNOOKERComponent {
  snookerInfo:SnookerAdat[] = [
    {
        helyezes:52,
        nev:"Alkani Sunny",
        orszag:"Thaiföld",
        nyeremeny:118500,
    },
    {
        helyezes:7,
        nev:"Allen Mark",
        orszag:"Észak-Írország",
        nyeremeny:681000,
    },
    {
        helyezes:72,
        nev:"Anda Zhang",
        orszag:"Kína",
        nyeremeny:44750,
    },
    {
        helyezes:76,
        nev:"Astley John",
        orszag:"Anglia",
        nyeremeny:40000,
    },
    {
        helyezes:73,
        nev:"Baird Sam",
        orszag:"Anglia",
        nyeremeny:44750,
    },
    {
        helyezes:13,
        nev:"Bingham Stuart",
        orszag:"Anglia",
        nyeremeny:345500,
    },
    {
        helyezes:97,
        nev:"Bingyu Chang",
        orszag:"Kína",
        nyeremeny:6750,
    },
    {
        helyezes:28,
        nev:"Brecel Luca",
        orszag:"Belgium",
        nyeremeny:179000,
    },
    {
        helyezes:79,
        nev:"Brown Jordan",
        orszag:"Észak-Írország",
        nyeremeny:29000,
    },
    {
        helyezes:78,
        nev:"Burden Alfred",
        orszag:"Anglia",
        nyeremeny:32000,
    },
    {
        helyezes:50,
        nev:"Carrington Stuart",
        orszag:"Anglia",
        nyeremeny:121750,
    },
    {
        helyezes:16,
        nev:"Carter Ali",
        orszag:"Anglia",
        nyeremeny:289000,
    },
    {
        helyezes:81,
        nev:"Carty Ashley",
        orszag:"Anglia",
        nyeremeny:22750,
    },
    {
        helyezes:86,
        nev:"Chandler Harvey",
        orszag:"Anglia",
        nyeremeny:14475,
    },
    {
        helyezes:83,
        nev:"Chuan Leong Thor",
        orszag:"Malajzia",
        nyeremeny:16500,
    },
    {
        helyezes:84,
        nev:"Clarke Jamie Rhys",
        orszag:"Wales",
        nyeremeny:15500,
    },
    {
        helyezes:63,
        nev:"Craigie Sam",
        orszag:"Anglia",
        nyeremeny:78500,
    },
    {
        helyezes:94,
        nev:"Dale Dominic",
        orszag:"Wales",
        nyeremeny:8750,
    },
    {
        helyezes:61,
        nev:"Davis Mark",
        orszag:"Anglia",
        nyeremeny:145725,
    },
    {
        helyezes:20,
        nev:"Day Ryan",
        orszag:"Wales",
        nyeremeny:244250,
    },
    {
        helyezes:18,
        nev:"Ding Junhui",
        orszag:"Kína",
        nyeremeny:270250,
    },
    {
        helyezes:64,
        nev:"Doherty Ken",
        orszag:"Írország",
        nyeremeny:77250,
    },
    {
        helyezes:29,
        nev:"Donaldson Scott",
        orszag:"Skócia",
        nyeremeny:176750,
    },
    {
        helyezes:21,
        nev:"Dott Graeme",
        orszag:"Skócia",
        nyeremeny:237750,
    },
    {
        helyezes:66,
        nev:"Dunn Mike",
        orszag:"Anglia",
        nyeremeny:74750,
    },
    {
        helyezes:53,
        nev:"Ebdon Peter",
        orszag:"Anglia",
        nyeremeny:111750,
    },
    {
        helyezes:88,
        nev:"Feilong Chen",
        orszag:"Kína",
        nyeremeny:13500,
    },
    {
        helyezes:22,
        nev:"Ford Tom",
        orszag:"Anglia",
        nyeremeny:212250,
    },
    {
        helyezes:57,
        nev:"Fu Marco",
        orszag:"Hong Kong",
        nyeremeny:104250,
    },
    {
        helyezes:51,
        nev:"Georgiou Michael",
        orszag:"Ciprus",
        nyeremeny:119600,
    },
    {
        helyezes:11,
        nev:"Gilbert David",
        orszag:"Anglia",
        nyeremeny:412000,
    },
    {
        helyezes:33,
        nev:"Gould Martin",
        orszag:"Anglia",
        nyeremeny:160250,
    },
    {
        helyezes:99,
        nev:"Grace David",
        orszag:"Anglia",
        nyeremeny:6750,
    },
    {
        helyezes:24,
        nev:"Guodong Xiao",
        orszag:"Kína",
        nyeremeny:211600,
    },
    {
        helyezes:61,
        nev:"Hamilton Anthony",
        orszag:"Anglia",
        nyeremeny:92250,
    },
    {
        helyezes:25,
        nev:"Haotian Lyu",
        orszag:"Kína",
        nyeremeny:191750,
    },
    {
        helyezes:10,
        nev:"Hawkins Barry",
        orszag:"Anglia",
        nyeremeny:427250,
    },
    {
        helyezes:91,
        nev:"Heathcote Louis",
        orszag:"Anglia",
        nyeremeny:10750,
    },
    {
        helyezes:6,
        nev:"Higgins John",
        orszag:"Skócia",
        nyeremeny:743000,
    },
    {
        helyezes:59,
        nev:"Higginson Andrew",
        orszag:"Anglia",
        nyeremeny:96250,
    },
    {
        helyezes:60,
        nev:"Highfield Liam",
        orszag:"Anglia",
        nyeremeny:96000,
    },
    {
        helyezes:89,
        nev:"Hirani Kishan",
        orszag:"Wales",
        nyeremeny:13350,
    },
    {
        helyezes:44,
        nev:"Holt Michael",
        orszag:"Anglia",
        nyeremeny:133500,
    },
    {
        helyezes:70,
        nev:"Honghao Luo",
        orszag:"Kína",
        nyeremeny:65000,
    },
    {
        helyezes:95,
        nev:"Jiahui Si",
        orszag:"Kína",
        nyeremeny:7500,
    },
    {
        helyezes:87,
        nev:"Jiankang Zhang",
        orszag:"Kína",
        nyeremeny:13600,
    },
    {
        helyezes:71,
        nev:"Jones Jak",
        orszag:"Wales",
        nyeremeny:54250,
    },
    {
        helyezes:48,
        nev:"Joyce Mark",
        orszag:"Anglia",
        nyeremeny:125750,
    },
    {
        helyezes:30,
        nev:"King Mark",
        orszag:"Anglia",
        nyeremeny:166500,
    },
    {
        helyezes:100,
        nev:"Langning Bai",
        orszag:"Kína",
        nyeremeny:5000,
    },
    {
        helyezes:92,
        nev:"Lee Andy",
        orszag:"Anglia",
        nyeremeny:9500,
    },
    {
        helyezes:43,
        nev:"Li Hang",
        orszag:"Kína",
        nyeremeny:138000,
    },
    {
        helyezes:36,
        nev:"Liang Wenbo",
        orszag:"Kína",
        nyeremeny:154500,
    },
    {
        helyezes:80,
        nev:"Lines Oliver",
        orszag:"Anglia",
        nyeremeny:28000,
    },
    {
        helyezes:12,
        nev:"Lisowski Jack",
        orszag:"Anglia",
        nyeremeny:392250,
    },
    {
        helyezes:34,
        nev:"Maflin Kurt",
        orszag:"Norvégia",
        nyeremeny:158600,
    },
    {
        helyezes:14,
        nev:"Maguire Stephen",
        orszag:"Skócia",
        nyeremeny:316000,
    },
    {
        helyezes:96,
        nev:"Mann Mitchell",
        orszag:"Anglia",
        nyeremeny:7500,
    },
    {
        helyezes:32,
        nev:"McGill Anthony",
        orszag:"Skócia",
        nyeremeny:16500,
    },
    {
        helyezes:54,
        nev:"McManus Alan",
        orszag:"Skócia",
        nyeremeny:111250,
    },
    {
        helyezes:85,
        nev:"Miah Hammad",
        orszag:"Anglia",
        nyeremeny:15475,
    },
    {
        helyezes:39,
        nev:"Milkins Robert",
        orszag:"Anglia",
        nyeremeny:149600,
    },
    {
        helyezes:8,
        nev:"Murphy Shaun",
        orszag:"Anglia",
        nyeremeny:506500,
    },
    {
        helyezes:62,
        nev:"Ning Lu",
        orszag:"Kína",
        nyeremeny:87250,
    },
    {
        helyezes:67,
        nev:"O'Brien Fergal",
        orszag:"Írország",
        nyeremeny:70600,
    },
    {
        helyezes:68,
        nev:"O'Connor Joe",
        orszag:"Anglia",
        nyeremeny:69750,
    },
    {
        helyezes:42,
        nev:"O'Donnell Martin;Anglia",
        orszag:"Anglia",
        nyeremeny:145250,
    },
    {
        helyezes:2,
        nev:"Sullivan Ronnie",
        orszag:"Anglia",
        nyeremeny:1116000,
    },
    {
        helyezes:65,
        nev:"Pengfei Tian",
        orszag:"Kína",
        nyeremeny:75750,
    },
    {
        helyezes:15,
        nev:"Perry Joe",
        orszag:"Anglia",
        nyeremeny:292500,
    },


    {
        helyezes:23,
        nev:"Robertson Jimmy",
        orszag:"Anglia",
        nyeremeny:211725,
    },
    {
        helyezes:5,
        nev:"Robertson Neil",
        orszag:"Ausztrália",
        nyeremeny:834500,
    },
    {
        helyezes:35,
        nev:"Saengkham Noppon",
        orszag:"Thaiföld",
        nyeremeny:157000,
    },
    {
        helyezes:4,
        nev:"Selby Mark",
        orszag:"Anglia",
        nyeremeny:863000,
    },
    {
        helyezes:27,
        nev:"Selt Matthew",
        orszag:"Anglia",
        nyeremeny:180350,
    },
    {
        helyezes:49,
        nev:"Sijun Yuan",
        orszag:"Kína",
        nyeremeny:123000,
    },
    {
        helyezes:74,
        nev:"Slessor Elliot",
        orszag:"Anglia",
        nyeremeny:43500,
    },
    {
        helyezes:75,
        nev:"Steadman Craig",
        orszag:"Anglia",
        nyeremeny:40500,
    },
    {
        helyezes:90,
        nev:"Stefanow Adam",
        orszag:"Lengyelország",
        nyeremeny:12500,
    },
    {
        helyezes:46,
        nev:"Stevens Matthew",
        orszag:"LWales",
        nyeremeny:129750,
    },
    {
        helyezes:1,
        nev:"Trump Judd",
        orszag:"Anglia",
        nyeremeny:1270500,
    },
    {
        helyezes:37,
        nev:"Un-Nooh Thepchaiya",
        orszag:"Thaiföld",
        nyeremeny:151225,
    },
    {
        helyezes:98,
        nev:"Ursenbacher Alexander",
        orszag:"Svájc",
        nyeremeny:6750,
    },
    {
        helyezes:31,
        nev:"Vafaei Hossein",
        orszag:"Irán",
        nyeremeny:160500,
    },
    {
        helyezes:45,
        nev:"Wakelin Chris",
        orszag:"Anglia",
        nyeremeny:129975,
    },
    {
        helyezes:26,
        nev:"Walden Ricky",
        orszag:"Anglia",
        nyeremeny:18270,
    },
    {
        helyezes:77,
        nev:"Walker Lee",
        orszag:"Wales",
        nyeremeny:33000,
    },
    {
        helyezes:82,
        nev:"Wattana James",
        orszag:"Thaiföld",
        nyeremeny:17500,
    },
    {
        helyezes:56,
        nev:"Wells Daniel",
        orszag:"Wales",
        nyeremeny:104250,
    },
    {
        helyezes:58,
        nev:"White Michael",
        orszag:"Wales",
        nyeremeny:98250,
    },
    {
        helyezes:3,
        nev:"Williams Mark",
        orszag:"Wales",
        nyeremeny:1048250,
    },
    {
        helyezes:55,
        nev:"Williams Robbie",
        orszag:"Anglia",
        nyeremeny:107500,
    },
    {
        helyezes:19,
        nev:"Wilson Gary",
        orszag:"Anglia",
        nyeremeny:261100,
    },
    {
        helyezes:9,
        nev:"Wilson Kyren",
        orszag:"Anglia",
        nyeremeny:470500,
    },
    {
        helyezes:40,
        nev:"Woollaston Ben",
        orszag:"Anglia",
        nyeremeny:146350,
    },
    {
        helyezes:47,
        nev:"Xintong Zhao",
        orszag:"Kína",
        nyeremeny:125750,
    },
    {
        helyezes:69,
        nev:"Xiwen Mei",
        orszag:"Kína",
        nyeremeny:68000,
    },
    {
        helyezes:17,
        nev:"Yan Bingtao",
        orszag:"Kína",
        nyeremeny:285000,
    },
    {
        helyezes:93,
        nev:"Zhengyi Fan",
        orszag:"Kína",
        nyeremeny:9500,
    },
    {
        helyezes:38,
        nev:"Zhou Yuelong",
        orszag:"Kína",
        nyeremeny:150250,
    },
]}

export interface SnookerAdat{
helyezes:number,
nev:string,
orszag:string,
nyeremeny:number,
}
